import { useEffect, useId, useRef, useState } from 'react'
import type { RouterSource, SourceVerification, UpstreamRoute } from '../../types/router'
import { AlertTriangle, ArrowLeft, CheckCircle2, CircleAlert, ExternalLink, PlugZap, Power, Route, ShieldCheck, Trash2, Unplug } from 'lucide-react'
import { sourceConnectionLabel, useRouterStore } from '../../store/routerStore'

interface StatusPillProps { children: React.ReactNode; tone?: 'neutral' | 'good' | 'warn' | 'danger' }
function StatusPill({ children, tone = 'neutral' }: StatusPillProps) {
  const tones = { neutral: 'border-line bg-panel2 text-muted', good: 'border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300', warn: 'border-amber-500/30 bg-amber-500/10 text-amber-700 dark:text-amber-300', danger: 'border-red-500/30 bg-red-500/10 text-red-700 dark:text-red-300' }
  return <span className={`inline-flex rounded border px-2 py-0.5 text-[10px] font-semibold ${tones[tone]}`}>{children}</span>
}

export function RouterView() {
  const store = useRouterStore()
  const [selectedRouteId, setSelectedRouteId] = useState<string | null>(null)
  const selectedRoute = store.routes.find((route) => route.id === selectedRouteId) ?? null
  const selectedSource = selectedRoute ? store.sources.find((source) => source.id === selectedRoute.sourceId) : null
  const openSource = (sourceId: string) => setSelectedRouteId(store.createOrResumeRoute(sourceId))

  if (selectedRoute && selectedSource) return <RouteDetail route={selectedRoute} source={selectedSource} verification={store.verification?.routeId === selectedRoute.id ? store.verification : null} defaultRouteId={store.defaultRoute.routeId} defaultModelId={store.defaultRoute.modelId} onBack={() => setSelectedRouteId(null)} onDisconnect={() => setSelectedRouteId(null)} />

  return <div className="mx-auto max-w-6xl space-y-6 p-5 sm:p-8 select-text">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-line pb-5"><div><div className="mb-2 flex items-center gap-2 text-xs text-muted"><span>Settings</span><span>›</span><span>Agents</span><span>›</span><span className="font-semibold text-fg">Router</span></div><h1 className="flex items-center gap-2 text-xl font-bold text-fg"><Route className="size-5 text-brand" />BoxFox Router</h1><p className="mt-1 max-w-2xl text-xs text-muted">Connect upstream accounts, providers, and explicit endpoints to native BoxFox routes. All actions are deterministic mock flows.</p></div><StatusPill tone="warn">Mock mode · no network activity</StatusPill></header>
    <ConfiguredRoutes routes={store.routes} defaultRouteId={store.defaultRoute.routeId} onOpen={setSelectedRouteId} onRemove={store.removeRoute} />
    <section aria-labelledby="source-catalog"><div className="mb-3"><h2 id="source-catalog" className="text-sm font-semibold text-fg">Upstream source catalog</h2><p className="mt-1 text-xs text-muted">Choose one direct upstream source. BoxFox does not connect to other router products.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{store.sources.map((source) => <article key={source.id} className="flex min-w-0 flex-col rounded-xl border border-line bg-panel p-4 shadow-xs"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-semibold text-fg">{source.name}</h3><StatusPill tone={source.adapterAvailable ? 'neutral' : 'warn'}>{source.adapterAvailable ? sourceConnectionLabel(source.connectionMethod) : 'Adapter required'}</StatusPill></div><p className="mt-2 text-xs leading-5 text-muted">{source.summary}</p><p className="mt-3 min-h-9 text-[11px] leading-4 text-muted/90">{source.caveat}</p><button type="button" onClick={() => openSource(source.id)} className="mt-4 inline-flex items-center justify-center gap-1.5 rounded-md border border-line bg-panel2 px-3 py-2 text-xs font-semibold text-fg hover:border-brand hover:text-brand"><PlugZap className="size-3.5" />{store.routes.some((route) => route.sourceId === source.id && !['connected', 'disconnected'].includes(route.state)) ? 'Resume setup' : 'Set up route'}</button></article>)}</div></section>
  </div>
}

function ConfiguredRoutes({ routes, defaultRouteId, onOpen, onRemove }: { routes: UpstreamRoute[]; defaultRouteId: string | null; onOpen: (id: string) => void; onRemove: (id: string) => void }) {
  if (!routes.length) return null
  return <section aria-labelledby="configured-routes" className="rounded-xl border border-line bg-panel p-4"><div className="mb-3"><h2 id="configured-routes" className="text-sm font-semibold">Configured routes</h2><p className="mt-1 text-xs text-muted">Every saved route is shown here. Remove unfinished or disconnected routes you no longer want to keep.</p></div><div className="space-y-2">{routes.map((route) => { const isDefault = defaultRouteId === route.id; const removable = route.state !== 'connected'; return <div key={route.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-line bg-panel2 px-3 py-2"><button type="button" onClick={() => onOpen(route.id)} className="min-w-0 text-left hover:text-brand"><span className="font-medium text-fg">{route.displayName}</span><span className="ml-2 text-xs text-muted">{route.models.length} reported model{route.models.length === 1 ? '' : 's'}</span></button><span className="flex items-center gap-2"><StatusPill tone={route.state === 'connected' ? 'good' : route.state === 'unavailable' ? 'danger' : 'warn'}>{route.state.replaceAll('_', ' ')}</StatusPill>{isDefault && <StatusPill tone="good">Default for new sessions</StatusPill>}{removable && <button type="button" aria-label={`Remove ${route.displayName}`} onClick={() => onRemove(route.id)} className="rounded p-1.5 text-muted hover:bg-red-500/10 hover:text-red-600"><Trash2 className="size-3.5" /></button>}</span></div> })}</div></section>
}

function RouteDetail({ route, source, verification, defaultRouteId, defaultModelId, onBack, onDisconnect }: { route: UpstreamRoute; source: RouterSource; verification: SourceVerification | null; defaultRouteId: string | null; defaultModelId: string | null; onBack: () => void; onDisconnect: () => void }) {
  const store = useRouterStore()
  const [endpointText, setEndpointText] = useState(route.endpoint ?? '')
  const [endpointConsent, setEndpointConsent] = useState(false)
  const [dataUseConsent, setDataUseConsent] = useState(false)
  const [disconnectOpen, setDisconnectOpen] = useState(false)
  useEffect(() => { setEndpointText(route.endpoint ?? '') }, [route.id, route.endpoint])
  useEffect(() => { setEndpointConsent(false); setDataUseConsent(false) }, [route.endpoint, route.revision, verification?.id])
  const saveEndpoint = () => store.updateDraft(route.id, { endpoint: endpointText })
  const testEndpoint = () => {
    if (endpointText !== (route.endpoint ?? '')) { saveEndpoint(); return }
    store.verifyRoute(route.id, endpointConsent)
  }
  const statusMessage = route.state === 'testing' ? 'Testing exact endpoint in mock mode…' : verification ? `Verification ${verification.status} · simulated` : ''
  const isEndpoint = source.connectionMethod === 'explicit_local_endpoint'
  const canReview = route.state === 'ready_to_confirm' && verification?.status === 'passed' && verification.routeRevision === route.revision
  const endpointId = useId(); const endpointConsentId = useId(); const dataUseConsentId = useId()

  return <div className="mx-auto max-w-5xl space-y-5 p-5 sm:p-8 select-text"><div className="flex flex-wrap items-center justify-between gap-3 text-xs text-muted"><div className="flex items-center gap-2"><span>Settings</span><span>›</span><span>Agents</span><span>›</span><span>Router</span><span>›</span><span className="font-semibold text-fg">{source.name}</span></div><button type="button" onClick={onBack} className="inline-flex items-center gap-1.5 rounded px-2 py-1.5 hover:bg-panel2 hover:text-fg"><ArrowLeft className="size-3.5" />Back to routes</button></div>
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-line pb-5"><div><div className="mb-2 flex items-center gap-2"><StatusPill>{sourceConnectionLabel(source.connectionMethod)}</StatusPill>{route.state === 'connected' && <StatusPill tone="good">Connected</StatusPill>}{route.state === 'login_required' && <StatusPill tone="warn">Login required</StatusPill>}{route.state === 'unavailable' && <StatusPill tone="danger">Test failed</StatusPill>}</div><h1 className="text-xl font-bold">{route.displayName}</h1><p className="mt-1 text-xs text-muted">Native BoxFox route for {source.name}. No real authorization or provider request occurs in mock mode.</p></div>{route.state === 'connected' && <button type="button" onClick={() => setDisconnectOpen(true)} className="inline-flex items-center gap-1.5 rounded-md border border-red-500/40 px-3 py-2 text-xs font-semibold text-red-700 hover:bg-red-500/10 dark:text-red-300"><Unplug className="size-3.5" />Disconnect</button>}</header>
    <p aria-live="polite" className="sr-only">{statusMessage}</p>
    {route.state === 'adapter_required' ? <AdapterGuide source={source} /> : route.state === 'connected' ? <ConnectedRoute route={route} source={source} defaultRouteId={defaultRouteId} defaultModelId={defaultModelId} onDefault={store.setDefault} /> : <><section className="rounded-xl border border-line bg-panel p-4 sm:p-5" aria-busy={route.state === 'testing'}><h2 className="text-sm font-semibold">1. Source setup</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-fg">Route name<input aria-label="Route name" value={route.displayName} onChange={(event) => store.updateDraft(route.id, { displayName: event.target.value })} className="mt-1.5 w-full rounded-md border border-line bg-panel2 px-3 py-2 text-xs font-normal outline-hidden focus:border-brand" /></label><div className="rounded-md border border-line bg-panel2 px-3 py-2 text-xs"><span className="font-semibold">Access</span><p className="mt-1 text-muted">Only me · mock metadata</p></div></div>
      {isEndpoint && <div className="mt-4 space-y-3"><label htmlFor={endpointId} className="block text-xs font-semibold">Exact adapter or endpoint URL</label><input id={endpointId} aria-describedby={`${endpointId}-hint`} value={endpointText} onChange={(event) => { setEndpointText(event.target.value); setEndpointConsent(false); setDataUseConsent(false) }} onBlur={saveEndpoint} placeholder="http://localhost:3001/v1" className="w-full rounded-md border border-line bg-panel2 px-3 py-2 font-mono text-xs outline-hidden focus:border-brand" /><p id={`${endpointId}-hint`} className="text-[11px] leading-4 text-muted">Localhost refers to the BoxFox host. This mock never scans ports or contacts this address. URLs with credentials, secret query parameters, fragments, or metadata addresses are rejected.</p><div className="flex items-start gap-2"><input id={endpointConsentId} checked={endpointConsent} disabled={route.state === 'testing'} onChange={(event) => setEndpointConsent(event.target.checked)} type="checkbox" className="mt-0.5 accent-blue-500" /><label htmlFor={endpointConsentId} className="cursor-pointer text-xs">I approve testing this exact endpoint for reachability, authentication status, and model metadata only.</label></div><button type="button" onClick={testEndpoint} disabled={!endpointText.trim() || !endpointConsent || route.state === 'testing'} className="inline-flex items-center gap-1.5 rounded-md bg-brand px-3 py-2 text-xs font-semibold text-brandfg disabled:cursor-not-allowed disabled:opacity-50"><ShieldCheck className="size-3.5" />{route.state === 'testing' ? 'Testing (mock)…' : 'Test endpoint (mock)'}</button></div>}
      {!isEndpoint && route.state === 'draft' && <button type="button" onClick={() => store.beginAuthorization(route.id)} className="mt-4 inline-flex items-center gap-1.5 rounded-md bg-brand px-3 py-2 text-xs font-semibold text-brandfg"><Power className="size-3.5" />Start account setup (mock)</button>}
      {route.state === 'login_required' && <Notice tone="warn" title="Login required"><p>A future adapter must use an officially supported method. This control simulates authorization and opens no OAuth page.</p><button type="button" onClick={() => store.completeMockAuthorization(route.id)} className="mt-3 rounded-md border border-amber-500/40 px-3 py-1.5 text-xs font-semibold hover:bg-amber-500/10">Simulate login & authorize</button></Notice>}
      {route.state === 'credential_required' && <Notice tone="warn" title="Credential reference required"><p>Choose a future host-held credential reference. This mock creates an opaque handle only; there is no key entry, OAuth flow, or backend call.</p><button type="button" onClick={() => store.completeMockCredentialReference(route.id)} className="mt-3 rounded-md border border-amber-500/40 px-3 py-1.5 text-xs font-semibold hover:bg-amber-500/10">Select host-held mock reference</button></Notice>}
      {route.state === 'unavailable' && <Notice tone="danger" title="Endpoint test failed"><p>{route.error}</p><button type="button" onClick={testEndpoint} disabled={!endpointConsent} className="mt-3 rounded-md border border-red-500/40 px-3 py-1.5 text-xs font-semibold hover:bg-red-500/10">Retry test</button></Notice>}
    </section>{verification && <p className={`text-xs ${verification.status === 'failed' ? 'text-red-600 dark:text-red-300' : 'text-muted'}`}>Verification {verification.status} · {verification.simulated ? 'simulated' : 'not simulated'}</p>}{canReview && <section className="rounded-xl border border-line bg-panel p-4 sm:p-5"><h2 className="text-sm font-semibold">2. Review data use</h2><p className="mt-2 text-xs leading-5 text-muted">Reported model metadata is available. Enabling this route means future prompts and tool results may be sent to this upstream source. This is a mock confirmation, not a backend policy grant.</p><div className="mt-4 rounded-lg border border-line bg-panel2 p-3 text-xs"><span className="font-semibold">Reported models</span><ul className="mt-2 space-y-1 text-muted">{route.models.map((model) => <li key={model.id}>{model.name} · capabilities remain reported or unknown</li>)}</ul></div><div className="mt-4 flex items-start gap-2"><input id={dataUseConsentId} checked={dataUseConsent} onChange={(event) => setDataUseConsent(event.target.checked)} type="checkbox" className="mt-0.5 accent-blue-500" /><label htmlFor={dataUseConsentId} className="cursor-pointer text-xs">I understand the future route may send session data to {source.name}.</label></div><button type="button" onClick={() => store.enableRoute(route.id, dataUseConsent, route.revision)} disabled={!dataUseConsent} className="mt-4 inline-flex items-center gap-1.5 rounded-md bg-brand px-3 py-2 text-xs font-semibold text-brandfg disabled:cursor-not-allowed disabled:opacity-50"><CheckCircle2 className="size-3.5" />Enable native route</button></section>}</>}
    {disconnectOpen && <DisconnectDialog route={route} isDefault={defaultRouteId === route.id} onCancel={() => setDisconnectOpen(false)} onDisconnect={() => { store.disconnectRoute(route.id); setDisconnectOpen(false); onDisconnect() }} />}
  </div>
}

function Notice({ tone, title, children }: { tone: 'warn' | 'danger'; title: string; children: React.ReactNode }) { const Icon = tone === 'warn' ? CircleAlert : AlertTriangle; return <div className={`mt-4 rounded-lg border p-3 ${tone === 'warn' ? 'border-amber-500/30 bg-amber-500/10' : 'border-red-500/30 bg-red-500/10'}`}><div className="flex gap-2"><Icon className={`mt-0.5 size-4 shrink-0 ${tone === 'warn' ? 'text-amber-600' : 'text-red-600'}`} /><div className="text-xs"><h3 className="font-semibold">{title}</h3><div className="mt-1 text-muted">{children}</div></div></div></div> }
function AdapterGuide({ source }: { source: RouterSource }) { return <section className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-5"><div className="flex gap-3"><PlugZap className="mt-0.5 size-5 shrink-0 text-amber-600" /><div><h2 className="text-sm font-semibold">Authorized adapter required</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-muted">{source.name} cannot route directly in this mock. Install and authorize a future BoxFox adapter, then provide one explicit endpoint you control. BoxFox will not intercept client traffic, install a certificate, read local token files, set a system proxy, or scan ports.</p><a href="https://github.com/q123w133/BoxFox-Agent-Box" className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-brand hover:underline">Read adapter requirements <ExternalLink className="size-3" /></a></div></div></section> }
function ConnectedRoute({ route, source, defaultRouteId, defaultModelId, onDefault }: { route: UpstreamRoute; source: RouterSource; defaultRouteId: string | null; defaultModelId: string | null; onDefault: (routeId: string, modelId: string) => void }) { return <section className="rounded-xl border border-line bg-panel p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">Connected models</h2><p className="mt-1 text-xs text-muted">Select one explicit default for new sessions. Fallback stays off.</p></div><StatusPill tone="good">Route enabled</StatusPill></div><div className="mt-4 space-y-2">{route.models.map((model) => { const selected = defaultRouteId === route.id && defaultModelId === model.id; return <div key={model.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-line bg-panel2 p-3"><div><p className="text-xs font-semibold">{model.name}</p><p className="mt-1 text-[11px] text-muted">Streaming: {model.capabilities.streaming}; tools: {model.capabilities.tools}; vision: {model.capabilities.vision}</p></div><button type="button" onClick={() => onDefault(route.id, model.id)} disabled={selected} className="rounded-md border border-line px-3 py-1.5 text-xs font-semibold hover:border-brand hover:text-brand disabled:border-emerald-500/40 disabled:text-emerald-700">{selected ? 'Default for new sessions' : 'Set as default'}</button></div> })}</div><p className="mt-4 text-[11px] text-muted">{source.name} model availability is a mock fixture and does not prove entitlement or verified capabilities.</p></section> }
function DisconnectDialog({ route, isDefault, onCancel, onDisconnect }: { route: UpstreamRoute; isDefault: boolean; onCancel: () => void; onDisconnect: () => void }) { const dialogRef = useRef<HTMLDivElement>(null); const opener = useRef<HTMLElement | null>(document.activeElement instanceof HTMLElement ? document.activeElement : null); useEffect(() => { const dialog = dialogRef.current; const buttons = dialog?.querySelectorAll<HTMLElement>('button'); buttons?.[0]?.focus(); const keyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { onCancel(); return } if (event.key !== 'Tab' || !buttons?.length) return; const first = buttons[0]; const last = buttons[buttons.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() } }; document.addEventListener('keydown', keyDown); return () => { document.removeEventListener('keydown', keyDown); opener.current?.focus() } }, [onCancel]); return <div className="fixed inset-0 z-60 flex items-center justify-center bg-black/60 p-4" role="presentation"><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="disconnect-title" aria-describedby="disconnect-description" className="w-full max-w-md rounded-xl border border-line bg-bg p-5 shadow-2xl"><h2 id="disconnect-title" className="text-base font-semibold">Disconnect {route.displayName}?</h2><p id="disconnect-description" className="mt-2 text-xs leading-5 text-muted">New requests will stop using this native route. {isDefault ? 'Its default selection will be cleared; no fallback is selected.' : 'Other route defaults will not change.'} Already-sent requests may finish. This does not sign out other apps or revoke an upstream grant.</p><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-md border border-line px-3 py-2 text-xs font-semibold hover:bg-panel2">Cancel</button><button type="button" onClick={onDisconnect} className="rounded-md bg-red-600 px-3 py-2 text-xs font-semibold text-white hover:bg-red-500">Disconnect route</button></div></div></div> }
